name: Test Flow Chain

on:
  workflow_dispatch:

concurrency:
  group: test_flow
  cancel-in-progress: true

jobs:
  first:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: logs/

  second:
    needs: [first]
    name: Second Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: arifsetyawan
          minimum-approvals: 1
          issue-title: "${{ github.run_id }} Approval Request"
          issue-body: ""
          exclude-workflow-initiator-as-approver: false
